name: Publish

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache_node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-v1-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-node-${{ env.cache-name }}-

      - name: Install
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install --no-progress --no-audit

      - name: Bootstrap
        run: npm run bootstrap

      - name: Test
        run: npm run ci

      - name: Authenticate with Registry
        if: success()
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish package
        if: success()
        run: npm run publish

  Skip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Skip Feedback
        run: echo "Workflow skipped via commit message"
