name: Release

on:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Configure CI Git User
        run: |
          git config --global user.name 'langaads'
          git config --global user.email 'langaads@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GH_TOKEN@github.com/devherobr/sdk
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Checkout and pull branch
        run: |
          git checkout "${GITHUB_REF:11}" 
          git pull

      - name: Cache node_modules
        uses: actions/cache@v1
        id: cache_node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-v1-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-v1-node-${{ env.cache-name }}-

      - name: Install
        if: steps.cache_node_modules.outputs.cache-hit != 'true'
        run: npm install --no-progress --no-audit

      - name: Bootstrap
        run: npm run bootstrap

      - name: Test
        run: npm run ci

      - name: Status
        run: git status

      - name: Create release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Status again
        run: git status

  Skip:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - name: Skip Feedback
        run: echo "Workflow skipped via commit message"
